---
title: "7-Oct-24"
format: html
---

## setup
```{r}
rm(list=ls())
library(tidyverse)
library(here)
```

# Data
```{r}
tomatoes <- read.csv(here("Data/tomatoes.csv"))
glimpse(tomatoes)
```


```{r}
tomatoes$Treatment <- 
  as.factor(tomatoes$Treatment)
levels(tomatoes$Treatment) # shows 4 different levels which is wrong

fix <- which(tomatoes$Treatment == "control")
tomatoes$Treatment[fix] <- "Control"

fix2 <- which(tomatoes$Treatment == "fertilizer")
tomatoes$Treatment[fix2] <- "Fertilizer"
levels(tomatoes$Treatment)
tomatoes$Treatment <- factor(tomatoes$Treatment)
```

```{r}
tomatoes |> mutate(Treatment = 
                     case_when(Treatment == "fertilizer" ~ "Fertilizer",
                               Treatment == "control" ~ "Control"))
                               
```

# calculating 5 number summary
```{r}
grades <- c(90,94,96,90,84,86)

# min
min(grades)
84

# max
max(grades)
96

# mean
(90+94+96+90+84+86)/6
90

# median
median(grades)
90

# 1st quartile
96-84
12*.25+84
87

3rd quartile
96-(12*.25)
93
```

