---
title: "9-Oct-24"
author: "S.O'Brien"
format: html
---

## setup
```{r}
rm(list=ls())
library(tidyverse)
library(here)
```

## read in tomato data
```{r}
tomatoes <- read.csv(here("Data/tomatoes.csv"))
```

## return 3rd, 7th, and 9th row
```{r}
tomatoes |> slice(c(3, 7, 9)) |> view()
```

## find all of the plants from the fertilizer treatment with avg_tomato_weight_g > or equal to 145 g
```{r}
tomatoes$Treatment <- 
  as.factor(tomatoes$Treatment)
levels(tomatoes$Treatment) # shows 4 different levels which is wrong

fix <- which(tomatoes$Treatment == "control")
tomatoes$Treatment[fix] <- "Control"

fix2 <- which(tomatoes$Treatment == "fertilizer")
tomatoes$Treatment[fix2] <- "Fertilizer"
levels(tomatoes$Treatment)
tomatoes$Treatment <- factor(tomatoes$Treatment)

tomatoes |>
  filter(Treatment == "Fertilizer" & 
           Avg_tomato_weight_g >= 145) |>
  view()
```

## make output folder
```{r}
dir.create(here("outputs"))
```

## save updated file
```{r}
write.csv(tomatoes,here("outputs",
                        "tomatoes_fixed.csv"), row.names = FALSE)

toms2 <- read.csv(here("outputs", "tomatoes_fixed.csv"))
```

## import NoCoLead data
```{r}
nocolead <- read.csv(here("Data/NoCoLead.csv"))
```

## avg number of tests given in data set
```{r}
nocolead |>
  summarise(avg_tests = mean(num_tests)) |>
  view()
```

## mean number tests per year
```{r}
nocolead |>
  group_by(Year) |>
  summarise(avg_test = mean(num_tests)) |>
  view()
```

